 create table cafe (
       cafe_id bigint not null,
        area varchar(255),
        city varchar(255),
        name varchar(255),
        phone_number varchar(255),
        rating double,
        primary key (cafe_id)
    )

      create table comment (
           id bigint not null,
            content varchar(255),
            post_id bigint,
            primary key (id)
        )

        create table member (
               member_id bigint generated by default as identity,
                profile_image_url varchar(512) not null,
                provider_type varchar(20) not null,
                role_type varchar(20) not null,
                user_id varchar(64),
                username varchar(100) not null,
                primary key (member_id)
            )

                create table post (
                   post_id bigint not null,
                    create_date timestamp,
                    modified_date timestamp,
                    appointment_date date,
                    content varchar(255),
                    imageurl varchar(255),
                    participation integer,
                    title varchar(255),
                    views integer,
                    user_id bigint,
                    theme_id bigint,
                    primary key (post_id)
                )

                create table review (
                   id bigint not null,
                    content varchar(255),
                    likes integer,
                    rating double,
                    member_id bigint,
                    theme_id bigint,
                    primary key (id)
                )

                    create table theme (
                       theme_id bigint not null,
                        appropriated_people integer,
                        cost integer,
                        description varchar(1000),
                        genre varchar(255),
                        imageurl varchar(255),
                        name varchar(255),
                        rating double,
                        time_limitation integer,
                        cafe_id bigint,
                        primary key (theme_id)
                    )

                        create table user_refresh_token (
                           refresh_token_seq bigint generated by default as identity,
                            refresh_token varchar(256) not null,
                            user_id varchar(64) not null,
                            primary key (refresh_token_seq)
                        )