spring:
  datasource:
    url: jdbc:postgresql://awseb-e-3pjvycjfe3-stack-awsebrdsdatabase-0bemblk2jlbm.chg3dsn71mku.ap-northeast-2.rds.amazonaws.com/postgres
    username: woohobi
    password: password!
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
