spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/escaper
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true