spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:h2:tcp://localhost/~/escaper
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#    show-sql: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
#        type:
#          descriptor:
#            sql: trace
#            BasicBinder: trace
