spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 189878761535-0ml018p4bn7qsg8c3hgotiss3qfddccg.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          kakao:
            client-id: 7009e70b6407e1f57a45b3572e88fef8
            client-secret: N7ylu2PWpjXDCf5MKw46Gk2w4z4Y1rdy
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id




# jwt secret key ??
jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'


# cors 설정
cors:
  allowed-origins: http://localhost:3000, https://escaper-front.vercel.app
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect