spring:
  profiles:
    active: dev
    group:
      dev:
        dev, oauth
      local:
        local, oauth


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'