spring:
  datasource:
    url: jdbc:postgresql://awseb-e-jei942ry68-stack-awsebrdsdatabase-98ye2nxqohlf.chg3dsn71mku.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: woohobi
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
